# Warning! This is auto-generated SQL & LookML, generated by csv-sql.web.app.
# Doublecheck the dimensions and their datatypes and adjust where necessary.

# explore: csv_to_sql_query {}

view: Test_Review_2 {
  derived_table: {
    sql:
      SELECT
        '25-05-2019' AS date, 'AAA' AS _location, 'A1' AS _product_line, 1000 AS _revenue
      UNION ALL
      SELECT
        '25-05-2019' AS date, 'AAA' AS _location, 'A2' AS _product_line, 2000 AS _revenue
      UNION ALL
      SELECT
        '25-05-2019' AS date, 'AAA' AS _location, 'A4' AS _product_line, 3000 AS _revenue
      UNION ALL
      SELECT
        '25-05-2019' AS date, 'BBB' AS _location, 'A3' AS _product_line, 4000 AS _revenue
      UNION ALL
      SELECT
        '25-05-2019' AS date, 'CCC' AS _location, 'A3' AS _product_line, 5000 AS _revenue

      ;;
  }

  dimension: date {
    type: string
    sql: ${TABLE}.date ;;
  }

  dimension: _location {
    type: string
    sql: ${TABLE}._location ;;
  }

  dimension: _product_line {
    type: string
    sql: ${TABLE}._product_line ;;
  }

  dimension: _revenue {
    type: number
    sql: ${TABLE}._revenue ;;
  }

  measure: total_revenue {
    type: sum
    sql: ${_revenue} ;;
  }

  dimension: case_when_Location {
    type: string
    case: {
      when: {
        sql: ${_location} = 'AAA' ;;
        label: "AAA"}
      when: {
        sql: ${_location} = 'BBB' ;;
        label: "BBB"}
      when: {
        sql: ${_location} = 'CCC' ;;
        label: "CCC"}
    }
}

  measure: count {
    type: count
  }
}
